### Health check

GET {{base_url}}/api/health

### Refresh token

POST {{base_url}}/api/auth/token/refresh
Content-Type: application/json

{
  "token": "{{refresh_token}}"
}

### Validate token

GET {{base_url}}/api/auth/token/validate
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Invalidate token

POST {{base_url}}/api/auth/token/invalidate
Content-Type: application/json
Authorization: Bearer {{access_token}}
