### Health check

GET {{base_url}}/api/health

### Login

POST {{base_url}}/api/auth/login
Content-Type: application/json

{
  "username": "",
  "password": ""
}

### Register

POST {{base_url}}/api/auth/register
Content-Type: application/json

{
  "username": "",
  "password": ""
}

### Refresh token

POST {{base_url}}/api/auth/token/refresh
Content-Type: application/json

{
  "token": "{{refresh_token}}"
}

### Validate token

GET {{base_url}}/api/auth/token/validate
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Invalidate token

POST {{base_url}}/api/auth/token/invalidate
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Reset password

POST {{base_url}}/api/auth/password/reset
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "username": ""
}

### Change password

POST {{base_url}}/api/auth/password/change
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "oldPassword": "",
  "newPassword": ""
}
