### Get all

GET {{base_url}}/api/quizzes
Authorization: Bearer {{access_token}}

### Get one

GET {{base_url}}/api/quizzes/sdklfjdsl
Authorization: Bearer {{access_token}}

### Create

POST {{base_url}}/api/quizzes
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "context": ""
}
